

## Chapter 1 Normed Spaces

_There are only two kinds of math books: those you cannot read beyond the first sentence, and those you cannot read beyond the first page._

C. N. Yang

_What we hope ever to do with ease, we must learn first to do with diligence._

Samuel Johnson

We now set off on an expedition through the vast subject of functional analysis. No doubt the reader has some familiarity with this place, and will recognize some of the early landmarks of the journey. Our starting point is the study of _normed spaces_, which are situated at the confluence of two far-reaching mathematical abstractions: vector spaces, and topology.

### 1.1 Basic definitions

The setting is that of a vector space over the real numbers \(\mathbb{R}\). There are a dozen or so axioms that define a vector space (the number depends on how they are phrased), bearing upon the existence and the properties of certain operations called addition and scalar multiplication. It is more than probable that the reader is fully aware of these, and we shall say no more on the matter. We turn instead to the central idea of this chapter.

A **norm** on the vector space \(X\) corresponds to a reasonable way to measure the _size_ of an element, one that is consistent with the vector operations. Given a point \(x\in X\), the norm of \(x\) is a nonnegative number, designated \(\|\,x\,\|\). We also write \(\|\,x\,\|_{X}\) at times, if there is a need to distinguish this norm from others. In order to be a norm, the mapping \(x\mapsto\,\|\,x\,\|\) must possess the following properties:

* \(\|\,x\,\|\,\geqslant\,0\,\,\,\forall x\in X\) ; \(\|\,x\,\|\,=\,0\) if and only if \(x=0\) (_positive definiteness_);
* \(\|\,x+y\,\|\,\leqslant\,\|\,x\,\|+\|\,y\,\|\,\,\,\forall x,y\in X\) (_the triangle inequality_);
* \(\|\,tx\,\|\,=\,|\,t\,|\,\|\,x\,\|\,\,\,\forall t\in\mathbb{R}\), \(x\in X\) (_positive homogeneity_).

Once it has been equipped with a norm, the vector space \(X\), or, more precisely perhaps, the pair \((X,\,\|\cdot\|\,)\), is referred to as a **normed space**.

