We have implied that vector spaces and topology are to meet in this chapter; where, then, is the topology? The answer lies in the fact that a norm induces a **metric** on \(X\) in a natural way: the distance \(d\) between \(x\) and \(y\) is \(d(x,y)=\|\,x-y\,\|\). Thus, a normed space is endowed with a metric topology, one (and this is a crucial point) which is compatible with the vector space operations.

#### 2.0.1 Some notation.

The closed and open **balls** in \(X\) are (respectively) the sets of the form

\[B(x,r)\,=\,\bigl{\{}\,y\in X\,:\,\|\,y-x\,\|\,\leqslant\,r\,\bigr{\}},\,\,\,B^{ \,\circ}(x,r)\,=\,\bigl{\{}\,y\in X\,:\,\|\,y-x\|<r\,\bigr{\}}\,,\]

where the radius \(r\) is a positive number. We sometimes write \(B\) or \(B_{X}\) for the closed unit ball \(B(0,1)\), and \(B^{\,\circ}\) for the open unit ball \(B^{\,\circ}(0,1)\). A subset of \(X\) is **bounded** if there is a ball that contains it.

If \(A\) and \(C\) are subsets of \(X\) and \(t\) is a scalar (that is, an element of \(\mathbb{R}\)), the sets \(A+C\) and \(tA\) are given by

\[A+C\,=\,\bigl{\{}\,a+c\,:\,a\in A\,,\,c\in C\,\bigr{\}},\quad tA\,=\,\bigl{\{} \,ta\,:\,a\in A\,\bigr{\}}.\]

(Warning: \(A+A\) is different from \(2A\) in general.) Thus, we have \(B\bigl{(}x,r\bigr{)}=\bigl{\{}x\bigr{\}}+r\,B\). We may even ask the reader to tolerate the notation \(B(x,r)=x+r\,B\). The **closure** of \(A\) is denoted \(\mathrm{cl}A\) or \(\overline{A}\), while its **interior** is written \(\mathrm{int}\,A\) or \(A^{\,\circ}\).

Given two points \(x\) and \(y\) in \(X\), the **closed interval** (or segment) \([x,y]\) is defined as follows:

\[[x,y]\,=\,\bigl{\{}\,z\,=\,(1-t)\,x+t\,y\,:\,t\in[0,1]\,\bigr{\}}.\]

When \(t\) is restricted to \((0,1)\) in the definition, we obtain the open interval \((x,y)\). The half-open intervals \([x,y)\) and \((x,y]\) are defined in the evident way, by allowing \(t\) to vary in \([0,1)\) and \((0,1]\) respectively.

The compatibility between the vector space and its norm topology manifests itself by the fact that if \(U\) is an open subset of \(X\), then so is its translate \(x+U\) and its scalar multiple \(tU\) (if \(t\neq 0\)). This follows from the fact that balls, which generate the underlying metric topology, cooperate most courteously with the operations of translation and dilation:

\[B(x,r)\,=\,x+B(0,r)\,,\,\,\,\,B(0,tr)\,=\,t\,B(0,r)\,\,\,(t\,>0)\,.\]

It follows from this, for example, that we have \(\mathrm{int}\,(tA)=t\,\mathrm{int}\,A\) when \(t\neq 0\), and that a sequence \(x_{i}\) converges to a limit \(x\) if and only if the difference \(x_{i}-x\) converges to \(0\). There are topologies on \(X\) that do not respect the vector operations in this way, but they are of no interest to us. We shall have good reasons later on to introduce certain topologies on \(X\) that _differ_ from that of the norm; they too, however, will be compatible with the vector operations.

